### ISSUE TITLE
Investigate ways to power Raspberry PIs from alternate 5V source

### ISSUE THREAD

**Issue by obscurerichard** [ModusCreateOrg/network-rgb-matrix-display#5]
# Notes from our Slack on powering the RPi4 from 5V PSUs:

Thursday, Aug 22nd, 2019

Jay Garcia 11:52 AM
sergiu should be able to power RPi4s via direct +5V @ 3Amps via direct connection to the GPIO Pins.

https://www.tomshardware.com/reviews/raspberry-pi-gpio-pinout,6122.html

Richard:
Lots of caveats in there though- no voltage regulator, no fuse. Be super careful... what 5V supply would we connect it to?
27 replies

Sergiu:
nothing special in mind. I know there is no voltage reg on that but we can use led quality level power supply

Sergiu:
these are really good quality and provide stable 5V

Jay Garcia:
we can use a small ATX power supply

Jay Garcia:
or the Chinly PSU we are driving the LEDs with

Richard:
Oooh, that’s 5V too? I couldn’t remember.., killing off one of the power supplies in the build would be awesome. What’s the part number for the Chinly supply?

Jay:
yes.
We would not be killing, but replacing.

Jay Garcia:
right now, this is a thought experiment. Not worth your time, Richard. :slightly_smiling_face:

Richard:
I :heart: thought experiments though. It would be cool if we could run some more 5V power off those Chinly PSUs, the Pis are not going to use very much power each.  Maybe drawing 10A max? Probably much more like 5A unless we're really maxing out the power consumption. (edited)

Sergiu:
the Pi 4 official power supply is 5V 3A

Richard:
So 4x would be 5V 16A max

Sergiu:
yes, the problem is that here we care about having stable V.
On LEDs we have A stable

Sergiu:
For the Ro office I can get an A grade 20A 5V voltage regulated PSU (edited)

Sergiu:
maybe with the 16A we are to close to the PSU peak ?

Richard:
Depends on the power factor and possibly other concerns.

Sergiu:
A small PC PSU may be too much but that delivers really stable V on the rails

Sergiu:
usually PF is 0,9 on the good PSUs as I remember. I may be wrong (edited)

Sergiu:
I am not very good with electronics, only things I did are arduino automation for reef aquariums. I know basics (edited)

Matthew Kelch:
I’m not sure how cheap the Chinly supplies were, but have we priced out the difference to a quality Mean Well supply instead when it comes to future iterations/public documentation?

Matthew:
I’m a bit picky when it comes to power supplies — I’ve had too many bad experiences with the cheap ones.

Jay:
I’ve had bad experiences too. Mainly PSUs fizzing out.  The Chinly psu seems to work very well.
The Project root folder has a spreadsheet that has links to most of the parts so that we can track details, etc. (edited)
:ok_hand:
1

Jay:
I got this from amazon in the USA https://www.amazon.ae/CHINLY-Universal-Regulated-Switching-Transformer/dp/B01M0EW9H7
amazon.aeamazon.ae
CHINLY 5V Power Supply, CHINLY 60A Universal Regulated Switching Power Supply Transformer For WS2811 2801 WS2812B WS2813 APA102 LED Strip Light, CCTV, Radio, Computer Project (DC5V 60A 300W)
CHINLY 5V Power Supply, CHINLY 60A Universal Regulated Switching Power Supply Transformer For WS2811 2801 WS2812B WS2813 APA102 LED Strip Light, CCTV, Radio, Computer Project (DC5V 60A 300W) Brand : CHINLY(13 kB)
https://images-na.ssl-images-amazon.com/images/I/41S6fCbMJrL._SR600,315_SCLZZZZZZZ_.jpg

Matthew:
https://www.meanwell.com/webapp/product/search.aspx?prod=RSP-320
meanwell.commeanwell.com
RSP-320-MEAN WELL Switching Power Supply Manufacturer
MEAN WELL Switching Power Supply. MEAN WELL is a Switching Power Supply manufacturer in Taiwan. – SMPS, SPS manufacturer, AC DC , DC DC , DC AC, industrial power supply, Medical power supply, Din Rail power supply, LED power supply, LED driver, charger, inverter, adaptor, rack power, modular configurable power, open frame power

Matthew:
The cool thing with the Meanwell supplies is that you can usually find a pre-existing design for a 3D printed cover as well: https://www.thingiverse.com/thing:2078123
thingiverse.comthingiverse.com
PSU Cover - Meanwell RSP 320 by toolson
Cover made for a Meanwell RSP 320 power supply. Switch hole is for a Marquardt 1801 series switch. Update: 06.Feb.2017: - minor changes

Matthew:
Not that it would be hard to design one for the Chinly :slightly_smiling_face:

Richard:
Oooh, only $42 for the RSP-320-5 https://www.amazon.com/Mean-RSP-320-5-Power-Supply-Signs/dp/B00IWC2RLS

Jay:
Nice. 60amps too

Richard:
I'm loving this review:
5 stars

The power supply easily handles the load

July 26, 2018
Verified Purchase

I am using one of these to power 16 Odroid XU4 computer boards. Running all of the boards uses around 240W which is 80% of what this unit can put out. The power supply easily handles the load. As others mentioned, the fan is a little loud for the amount of air it moves.

I measured the voltage when I first got it and it was a little below 5 volts so I used a small screwdriver to adjust it to exactly 5 volts.
It's been running continuously for several months now without a problem.

I'm planning to buy another one to power more Odroid computers. 
(edited)

Richard: 

https://www.aliexpress.com/item/32506618623.html
Ali Express is a rabbit hole, a beautiful, beautiful rabbit hole. Behold this power distribution board... maybe not the perfect one for this application, but in the neighborhood, especially if we are going to power Raspberry PIs directly from a single 5V power supply. This has fuses and is pre-populated with 2A fuses, which might work just fine for the RPis, given http://www.pidramble.com/wiki/benchmarks/power-consumption
How much amperage does each LCD panel draw?

aliexpress.comaliexpress.com
US $17.2 |5V 12V 24V DC power distribution 18 ch PCB board terminal block for switching power supply electricity current wiring LED switch-in Instrument Parts & Accessories from Tools on Aliexpress.com | Alibaba Group
Smarter Shopping, Better Living! Aliexpress.com
Jay Garcia 1:41 PM
shit. that's a nice find dude.
:awthanks:
1

Richard:
I liked their application picture. Look familiar ?

![image](https://user-images.githubusercontent.com/341082/64561692-5712be00-d319-11e9-9335-2032e46100f9.png)

**Comment by jaygarcia** [comment]
Closing issue for now. We've investigated =). Perhaps a new issue to implement in the future?

**Comment by jaygarcia** [comment]
re-opening as we're moving fwd w/ this change.
